
const resposne = {
  successTrue: true,
  successFalse: false,
  admincreate: 'Create Admin Successfull',
  adminfailed: "Failed To Create Admin",
  checkphone: "Phonenumber Already Registered",
  checkEmail: "Email Already Registered",
  checkusername: "Username Already Registered",
  internalerror: "Internal server Error. Please try again later.",
  loginuser: "Failed To Login Admin",
  adminlginsuccess: "Admin Login Success",
  invalidformat: "Invalid token format",
  invalidtoken: "Invalid token",
  unauth: "Unauthorized user, please provide a token",
  emailnotexist: "Invalid Email or Does not exist ",
  invalidpassword: "Invalid password",
  invaliduser: "Invalid user",
  updateSuccess: "Admin Profile updated successfully",
  updateFail: "Admin Profile update failed",
  otpsend: "OTP Sent Successfully ",
  otpverified: "OTP verified successfully",
  otpnotverified: "OTP NOT VERIFIED",
  noupdate: "No data provided for update",
  otpstorefailed: "Failed to store OTP", 
  otpverifyfailed: "Failed to verify OTP or Invalid otp",
  otpfailed: "Failed To Send Otp",
  createventfail: "Failed to create event.",
  createvent: "Event created successfully.",
  logobanner: "Both logo and banner images are required.",
  submisionlimit: "Submission limit is required and must be at least 1 when limiting submissions.",
  diffrentemail: "The additional email should be different from the main email.",
  awardcreate: "Award created successfully.",
  awardcreatefail: "Failed to create Award.",
  downloadSuccess: "File downloaded succesfully",
  fetchSuccess: "Data Fetched  Successfully",
  nodatavail: "failed to get Data",
  newPass: "New password and confirmation do not match.",
  missingPass: "Password is missing",
  novalidfield: "No valid fields to update",
  eventIdfail: "Invalid Event Id or not Found.",
  usernotfound: "User not found",
  errorchangePass: "An error occurred while changing the password",
  errorchangeverifyPass: "An error occurred while verifying the password",
  incorrectcurrentPass: "Current password is incorrect",
  hashingError: "An error occurred while hashing the password",
  updatePassError: "An error occurred while updating the password",
  passUpdateFail: "Password update failed",
  passChanged: "Password changed successfully",
  usercreate:"Create User Successfull",
  userlginsuccess: "User Login Success",
  usercreateEmailFail :"User created successfully, but failed to send email",
  newPassFail :"Error occured while creating new password",
  imageRequire :"Profile Image is required",
 is_start_REquired:  "Start date is required when is_start_date is 1.",
 is_end_REquired:  "End date is required when is_end_date is 1.",
 checkCurrentPass:"Invalid Password or does not match the exact Password",
 awardUpdateSuccess:"Awards Updated Successfully",
 awardUpdateFail:"Failed to Update Awards",
 awardDeleted:"Award Deleted Successfully",
 awardNotFound:"Award category Not found Or does not exist",
 deleteAwardError:"Error Occured while deleting the Award Category",
 awardalreadyDeleted:"Award Category Already deleted"
};
export default resposne
