
const resposne = {
  successTrue: true,
  successFalse: false,
  admincreate: 'Create Admin Successfull',
  adminfailed: "Failed To Create Admin",
  checkphone: "Phonenumber Already Registered",
  checkEmail: "Email Already Registered",
  checkusername: "Username Already Registered",
  internalerror: "Internal server Error. Please try again later.",
  loginuser: "Failed To Login Admin",
  adminlginsuccess: "Admin Login Success",
  invalidformat: "Invalid token format",
  invalidtoken: "Invalid token",
  unauth: "Unauthorized user, please provide a token",
  emailnotexist: "Invalid Email or Does not exist ",
  invalidpassword: "Invalid password",
  invaliduser: "Invalid user",
  updateSuccess: "Admin Profile updated successfully",
  updateFail: "Admin Profile update failed",
  otpsend: "OTP Sent Successfully ",
  otpverified: "OTP verified successfully",
  otpnotverified: "OTP NOT VERIFIED",
  noupdate: "No data provided for update",
  otpstorefailed: "Failed to store OTP",
  otpverifyfailed: "Failed to verify OTP or Invalid otp",
  otpfailed: "Failed To Send Otp",
  invalidOtp: "Invalid OTP",
  passupdateSuccess: "Password updated successfully",
  createventfail: "Failed to create event.",
  createvent: "Event created successfully.",
  logobanner: "Both logo and banner images are required.",
  submisionlimit: "Submission limit is required and must be at least 1 when limiting submissions.",
  diffrentemail: "The additional email should be different from the main email.",
  awardcreate: "Award created successfully.",
  awardcreatefail: "Failed to create Award.",
  downloadSuccess: "File downloaded succesfully",
  fetchSuccess: "Data Fetched Successfully",
  nodatavail: "failed to get Data",
  newPass: "New password and confirmation do not match.",
  missingPass: "Password is missing",
  novalidfield: "No valid fields to update",
  eventIdfail: "Invalid Event Id or not Found.",
  usernotfound: "User not found",
  errorchangePass: "An error occurred while changing the password",
  errorchangeverifyPass: "An error occurred while verifying the password",
  incorrectcurrentPass: "Current password is incorrect",
  hashingError: "An error occurred while hashing the password",
  updatePassError: "An error occurred while updating the password",
  passUpdateFail: "Password update failed",
  passChanged: "Password changed successfully",
  usercreate: "Create User Successfull",
  userlginsuccess: "User Login Success",
  usercreateEmailFail: "User created successfully, but failed to send email",
  newPassFail: "Error occured while creating new password",
  imageRequire: "Profile Image is required",
  is_start_REquired: "Start date is required when is_start_date is 1.",
  is_end_REquired: "End date is required when is_end_date is 1.",
  checkCurrentPass: "Invalid Password or does not match the exact Password",
  awardUpdateSuccess: "Awards Updated Successfully",
  awardUpdateFail: "Failed to Update Awards ",
  awardDeleted: "Award Deleted Successfully",
  awardNotFound: "Award category Not found Or does not exist",
  deleteAwardError: "Error Occured while deleting the Award Category",
  awardalreadyDeleted: "Award Category Already deleted",
  eventUpdateSuccess: "Events Updated Successfully",
  eventUpdateFail: "Failed to Update Event",
  updateventSuccess: "Event Updated Successfully",
  submissionFormatFail: "Failed to create Submission ID Format",
  submissionFormatSuccess: "Submission ID Format created successfully",
  noaffectedRowwithId: "No rows updated. Check if the event ID is valid.",
  SubmissionFormatUpdate: "Submission ID updated successfully",
  publicVisibleFalse: "Event can't be made visible to the public, error occurred.",
  publicVisibleTrue: "Event is now visible to the public.",
  draftTOLiveFail: "Event can't be made Live to the public, error occurred.",
  draftTOLiveSuccess: "Event is made Live now to the public.",
  overallScoreFail: "Failed to insert overall scores",
  generalSettingandUpdatedates: "Successfully created general settings and updated dates",
  noaffectedRowwithstartEnd: "No rows affected while updating start and end dates.",
  generalSettingsUpdatewithoutDate: "Successfully created general settings without updating dates",
  generalsettingsError: "An error occurred while creating general settings",
  noaffectedRows: "No rows affected",
  generalSettingsSuccess: "General settings created successfully",
  overallScoreINsertSuccess: "Overall score inserted successfully",
  overallvaluesFail: "Failed to insert some Overall Scorecard Values",
  overallScorecardValueSuccess: "Overall Scorecard Value inserted successfully",
  ScoreCradSuccess: "Scorecard Created Successfully",
  startEndUpdateSuccess: "Start And end date updated successfully",
  EventLiveSuccess: "Event Is posted Live successfully",
  EventArchiveSuccess: "Event Is Archived successfully",
  draftTOArchiveFail: "Event can't be Archived, error occurred.",
  criteriawithoutcaptionvalue: "Criteria settings created without Caption and value",
  criteriawithcaptionvalueSuccess: "Criteria settings with Caption and Value created successfully",
  criteriaNotFound: "Criteria Not found Or does not exist",
  criteriaDeleted: "Criteria Deleted Successfully",
  criteriaAlreadyDeleted: "Criteria Already deleted",
  noChangesMade: "The criteria and settings were already deleted or do not exist.",
  deleteCriteriaError: "Error Occured while deleting the Criteria",
  nodeletedSettingvalue: " No settings values were deleted, as they either don't exist or were already deleted.",
  nodeletedSetting: " No settings were deleted, as they either don't exist or were already deleted.",
  criteriaDeleteSuccess: "Criteria Deleted SuccessFully",
  nogroupCreate: "No group name was created.",
  insertFilteringCriteriafail: "Failed to insert some filtering criteria.",
  insertfilteringcriteriacategoryFail: "Failed to insert some filtering criteria categories.",
  FilteringCriteriaInsertSuccess: "Filtering Criteria inserted successfully",
  juryGroupCreateSuccess: "Jury group created successfully.",
  assignJuryCreateFail: "Failed to create assign jury: error occurred",
  assignJuryCreateSuccess: "Assign jury created successfully",
  additionalmailinsertFail: 'Failed to insert additional email',
  industrytypeInsertFail: 'Failed to insert industry type.',
  eventnotfound: "Event not found",
  insertORUpdateFail: 'Failed to update or insert additional email',
  invalidSocialplatform: 'Invalid social platform value. Allowed values are: facebook, linkedin, twitter.',
  noUpdateFieldProvided: "No update fields were provided.",
  dbUpdateFail: 'Database update failed.',
  scorecardCriteriaCreateFail: "Failed to create Scorecard Criteria",
  scorecardCriteriaCreateSuccess: "Scorecard Criteria created successfully",
  juryGroupNameCreateFail: "Failed to create Jury group name",
  jurygroupNameCreateSuccess: "Jury group name created successfully",
  filteringCriteriaCategoryCreateSuccess: "Filtering criteria category created successfully",
  assignJuryCreateFail: "Assign jury creation failed: No insert ID returned.",
}
export default resposne
